/**
 * Site config — city-specific values.
 *
 * To spin up a new city deployment (e.g., Calgary), fork the repo and edit
 * this file. Sell-landing URLs are city-agnostic paths (`/sell/<slug>/`) served
 * from a per-city domain, so they no longer carry a city slug; the local signal
 * lives in copy, schema, and the domain. `citySlug` is retained for city
 * identity but no longer drives sell-landing URL generation.
 */
module.exports = {
  // City
  citySlug: 'edmonton',
  cityName: 'Edmonton',
  province: 'Alberta',
  provinceCode: 'AB',
  country: 'CA',
  countryName: 'Canada',

  // Brand
  brandName: 'Edmonton Refreshed',
  brandFullName: 'Edmonton Refreshed Seating',
  brandTagline: 'Better furniture. Better experience.',
  brandStatement:
    'Edmonton Refreshed buys and resells premium pre-owned sofas and sectionals across Edmonton and surrounding areas.',
  brandSubstatement:
    'Viewings by appointment. Professionally inspected pieces from recognized brands.',

  // Contact
  phone: '780-965-1477',
  phoneDigits: '7809651477',
  email: 'info@edmontonrefreshed.com',

  // Business stats — update sitewide by editing here
  piecesSold: '40+',
  piecesBought: '41+',
  rating: '4.9',
  ratingCount: 18,
  offerRange: 'Most Offers $500–$2,500',

  // brandList — canonical ordered brand list for entity/AI surfaces (§2.1:
  // top-tier names lead; La-Z-Boy near the end, never first). Rendered between
  // BRAND_LIST_START/_END markers (homepage sr-only block, sold-page intro)
  // by build.js — edit here once, never per page.
  brandList: [
    'B&B Italia',
    'Natuzzi',
    'Rove Concepts',
    'Crate & Barrel',
    'EQ3',
    'West Elm',
    'American Leather',
    'Restoration Hardware',
    'La-Z-Boy',
    'Urban Barn',
    'Brentwood Classics',
  ],

  // sameAs — canonical external profile URLs for Knowledge Graph entity
  // consolidation. Read into every Organization / FurnitureStore schema by
  // build.js, and referenced by hand-maintained sameAs arrays in pages that
  // don't go through build.js (homepage FurnitureStore, about Organization,
  // sell hub FurnitureStore, sell-landing FurnitureStore schemas). Adding a
  // new profile (e.g. YouTube, Pinterest) — append the URL here and rebuild;
  // the hand-maintained pages still require a one-time manual sync.
  sameAs: [
    'https://maps.app.goo.gl/Nipdt38odihmKEfG7',     // Google Business Profile
    'https://www.facebook.com/edmontonrefreshed',
  ],

  // Canonical brand logo for structured data — the Organization /
  // FurnitureStore / LocalBusiness `logo` and every guide Article
  // `publisher.logo` point here, so search + Knowledge Graph consolidate one
  // logo for the entity (the same way `sameAs` consolidates profiles). It is
  // the horizontal wordmark on a WHITE background (raster PNG) so it stays
  // legible on any surface a search/AI panel renders it on — the nav + footer
  // use the transparent variant instead (§7.6). build.js threads it into
  // listing schemas and lints hand-maintained pages for drift; sync those
  // pages when this changes.
  logo: 'https://edmontonrefreshed.com/brand/er-logo-horizontal-onwhite.png',

  // Google Merchant Center product feed (/merchant-feed.xml) — generated by
  // build.js from available-data.js on every build. Google is pointed at the
  // public feed URL with a daily scheduled fetch; there is no server or cron.
  merchantFeed: {
    currency: 'CAD',
    // Flat local-delivery rate advertised in each item's shipping attribute.
    // Scoping shipping to a single region (below) makes Google treat the pieces
    // as locally available WITHOUT requiring national shipping rates. Mirrors
    // the $200 local-delivery rate used in the on-page Offer schema. Set to 0
    // to advertise free local delivery / pickup.
    //   · shippingRate: a number (e.g. 200) → emit <g:shipping> with country +
    //     price. 0 → free. null → omit <g:shipping> entirely and defer to the
    //     account-level shipping settings (the Merchant Center account targets
    //     Canada).
    //   · shippingRegion: '' → no <g:region> (recommended — Google rejected
    //     province-level region values, even ISO 3166-2 'CA-AB'). A value would
    //     re-add the sub-attribute that triggered the "invalid region" error.
    shippingRate: 200,
    shippingCountry: 'CA',
    shippingRegion: '',
    // Default Google product category — VERIFIED against Google's official
    // Product Taxonomy. Note: "Furniture" is a TOP-LEVEL category, NOT nested
    // under "Home & Garden" (that path is invalid). Sofas (id 460) covers
    // sofas, sectionals, and couches; build.js overrides per-piece for
    // chairs/ottomans. There is no standalone "Sectionals" node.
    googleProductCategory: 'Furniture > Sofas',
  },
};
